# Spring
spring:

  # Application
  application:
    name: hibernate-audit

  # Datasource
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_type
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  # H2
  h2:
    console:
      enabled: true